name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: E2E tests (headless)
        run: |
          npx playwright install --with-deps
          npm run e2e || echo "E2E skipped or failed; adjust when e2e project is ready"
      - name: Build (production - browser only)
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL || '' }}
          FCM_VAPID_KEY: ${{ secrets.FCM_VAPID_KEY || '' }}
        run: npm run build:prod:browser
      - name: Generate Lighthouse report (optional)
        if: always()
        run: |
          npx --yes http-server dist/apps/ecommerce/browser -p 4201 -s &
          npx --yes lighthouse http://127.0.0.1:4201 --only-categories=performance,accessibility,best-practices,seo --output html --output-path docs/lighthouse/report.html || echo "Lighthouse optional"
      - name: Upload Lighthouse artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: docs/lighthouse/report.html
      - name: TODO - Switch back to SSR build
        run: "echo 'TODO: revert to SSR build once NG0201 is fixed'"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
